### ISSUE TITLE
plotting trees with symbols containing "_" results in error

### ISSUE THREAD

**Issue by xgdgsc** [sisl/ExprOptimization.jl#14]
When plotting trees that contains symbol including underscore ("_"), which can be common in programming, the plotting engine would result in errors like
```latex
! Missing $ inserted.
<inserted text> 
$
l.67 }
    ;
``` 
I don' t know if there can be workarounds in this package or we should report to TreeView.jl?

**Comment by rcnlee** [comment]
Take a look at LaTeXStrings.jl. There should be a way with little to no modifications. Alternatively, you can manually escape the characters in your strings before passing them.

**Comment by xgdgsc** [comment]
Thanks, that would work for me.
