### ISSUE TITLE
Max_depth is not globally enforced

### ISSUE THREAD

**Issue by rcnlee** [sisl/ExprOptimization.jl#2]
When doing a crossover or mutation,  you can end up with trees that are deeper than max_depth.   The reason is that max_depth is not globally enforced at the moment.  It is only enforced relative to the substitution point.  

~~Also, there is currently a requirement for at least one terminal per type, which is restrictive.~~

**Comment by tawheeler** [comment]
- right, the way it is currently implemented, `max_depth` is the maximum depth of the generated subtree

**Comment by rcnlee** [comment]
That's a good idea, I'll break it out into a separate issue.  Although, it's likely that one fix will address both issues.

**Comment by rcnlee** [comment]
This is addressed in the latest set of changes.
