### ISSUE TITLE
The order of `evaluate!` and `fit_mle!` in CE

### ISSUE THREAD

**Issue by xukai92** [sisl/ExprOptimization.jl#25]
In the main loop of CE (below),
https://github.com/sisl/ExprOptimization.jl/blob/6d9a0255eed6b7bd10bd9cacadab2c2592953c41/src/CrossEntropy/CrossEntropys.jl#L106-L114
it seems to me that `fit_mle!` should be called before the loop to resample population, i.e. L109 to L111.
Otherwise the PCFG is always fit using `k` samples that are not actually sorted or so.
Do I miss anything here?

**Comment by rcnlee** [comment]
You're right!  It's unsorted where it is now.  That is a bug.  
Can you please submit a pull request? Thanks!

**Comment by rcnlee** [comment]
Resolved by #26
