### ISSUE TITLE
Non-derivation-tree-based algorithms and _()

### ISSUE THREAD

**Issue by rcnlee** [sisl/ExprOptimization.jl#5]
Similar issue to #4 

Grammatical evolution also has a similar issue.  The mapping from integer vector to derivation tree becomes non-deterministic in this case.  The value doesn't get concretized until derivation tree is created.

**Comment by mykelk** [comment]
Can it just be cached to make it deterministic?

**Comment by rcnlee** [comment]
The information would need to be bundled with the integer vector, and operators (crossover and mutation) would need to account for this.  For example, if you crossover two integer vectors, the meanings of the second half of the vector change rendering the cached values insensible.

***

=> Actually, the _() problem is much more widespread.  It affects all methods that do not use derivation trees as its primary representation.  

* Cross-entropy method stores the knowledge gained into probability vectors, which does not remember what are the good values generated by _().  
* Same with probabilistic prototype trees that also uses probability vectors over production rules.  (Although the paper describes a PPT-specific way to store Real values into the tree as a workaround)
* Algorithms that rely on the sequential decision form assume that a sequence of numbers uniquely describes a tree and can be enumerated (e.g., GE, MCTS, NMC, I-DFS)

**Comment by mykelk** [comment]
We can just throw an error if `_()` can't be supported or a warning for potentially unintended functionality depending on the particular algorithms.

**Comment by rcnlee** [comment]
Sounds good.  Implemented in d6d7cf9c9d6c3a0f11915de82e66faa6310223d4.

I'm closing for now.  Will reopen if things change.
