### ISSUE TITLE
Save tree to a .txt file?

### ISSUE THREAD

**Issue by flare9x** [sisl/ExprOptimization.jl#8]
Hi! 

So the output: 

`display(results_ge.tree, grammar)`

Can I save it as .txt file? 

I use the Atom - juno IDE. It runs but not sure how I see the display? 

Thanks
Andrew 

PS loving this package

**Comment by mykelk** [comment]
It uses `TikzGraphs.jl`, which generates an SVG through calls to lualatex and pdf2svg. 

If you want it pretty-printed in text, then I think we can use some of the `print_tree` functionality in `AbstractTrees.jl`. If you don't need it pretty-printed, then you can just display the expression (example based on the example Julia notebook):
```julia
results_mc = optimize(p, grammar, :Real, loss)
results_mc.expr
```

**Comment by rcnlee** [comment]
Thanks Andrew, feel free to star the repo and tell your friends!

I think saving the SVG image file is the best for visualizing the tree, or ``results_mc.expr`` for just displaying the expression, as Mykel said.

You can visualize the tree in text format and save it to text file as well.  The package is compatible with ``AbstractTrees.jl``.

```julia
using AbstractTrees
results_mc = optimize(p, grammar, :Real, loss)
f = open("./tree.txt")
print_tree(f, results_mc.expr)  #labels are the terminals
#alternatively,
#print_tree(f, results_mc.tree)  #labels are the rule numbers in the grammar
close(f)
```

**Comment by rcnlee** [comment]
I added a demo of the ``AbstractTrees.jl`` interface to the [example notebook](http://nbviewer.jupyter.org/github/sisl/ExprRules.jl/blob/master/examples/grammar.ipynb) of ``ExprRules.jl``.

**Comment by flare9x** [comment]
Gentlemen - Thank you kindly!!

**Comment by zsunberg** [comment]
You can also use https://github.com/sisl/D3Trees.jl if the tree is large
enough to be unwieldy to print. it should work with anything that
implements the AbstractTrees interface

**Comment by rcnlee** [comment]
Sure, happy to help.  I'm going to close.  Feel free to reopen if the issue is not solved.
